// Alle teksten van het intakeformulier in de drie talen die een kliniek kan kiezen.
// De antwoorden die bewaard worden, blijven altijd de Nederlandse waarde (w), zodat
// wisselen van taal niets aan de bewaarde gegevens verandert.

export type Taal = "nl" | "fr" | "en";

export const TALEN: { code: Taal; naam: string }[] = [
  { code: "nl", naam: "NL" },
  { code: "fr", naam: "FR" },
  { code: "en", naam: "EN" },
];

export const isTaal = (v: unknown): v is Taal => v === "nl" || v === "fr" || v === "en";

// Frans: "de" wordt "d'" voor een klinker of een stomme h ("d'Aesthetic Lounges").
export const deFr = (naam: string) => (/^[aeiouyhàâäéèêëîïôöûü]/i.test(naam.trim()) ? `d'${naam.trim()}` : `de ${naam.trim()}`);

export type Optie = { w: string; l: Record<Taal, string> };
const o = (nl: string, fr: string, en: string): Optie => ({ w: nl, l: { nl, fr, en } });

export const OPTIES = {
  talen: [o("Nederlands", "Néerlandais", "Dutch"), o("Frans", "Français", "French"), o("Engels", "Anglais", "English")],
  verplichteGegevens: [
    o("Voornaam", "Prénom", "First name"),
    o("Achternaam", "Nom", "Last name"),
    o("Telefoonnummer", "Numéro de téléphone", "Phone number"),
    o("E-mailadres", "Adresse e-mail", "Email address"),
    o("Behandeling", "Soin", "Treatment"),
    o("Datum en tijd", "Date et heure", "Date and time"),
    o("Voorkeursmedewerker", "Praticien préféré", "Preferred staff member"),
  ],
  agendaToegang: [
    o("Beschikbaarheid tonen én boeken", "Afficher les disponibilités et réserver", "Show availability and book"),
    o("Alleen beschikbaarheid tonen", "Afficher seulement les disponibilités", "Only show availability"),
    o("Alleen doorverwijzen", "Seulement rediriger", "Only refer on"),
  ],
  jaNee: [o("Ja", "Oui", "Yes"), o("Nee", "Non", "No"), o("Onder voorwaarden", "Sous conditions", "Under conditions")],
  magZelfstandig: [
    o("Algemene vragen beantwoorden", "Répondre aux questions générales", "Answer general questions"),
    o("Prijzen communiceren", "Communiquer les prix", "Share prices"),
    o("Afspraken maken", "Prendre des rendez-vous", "Book appointments"),
    o("Afspraken verplaatsen", "Déplacer des rendez-vous", "Reschedule appointments"),
    o("Klantgegevens verzamelen", "Collecter les données clients", "Collect client details"),
    o("Behandelingen uitleggen", "Expliquer les soins", "Explain treatments"),
    o("Promoties communiceren", "Communiquer les promotions", "Share promotions"),
    o("Een consult voorstellen", "Proposer une consultation", "Suggest a consultation"),
  ],
  situaties: [
    o("Klant vraagt om een medewerker", "Le client demande un collaborateur", "Client asks for a staff member"),
    o("Klacht of ontevreden klant", "Plainte ou client mécontent", "Complaint or unhappy client"),
    o("Medische of specialistische vraag", "Question médicale ou spécialisée", "Medical or specialist question"),
    o("Terugbetaling", "Remboursement", "Refund"),
    o("Betalingsprobleem", "Problème de paiement", "Payment problem"),
    o("Uitzondering op de regels", "Exception aux règles", "Exception to the rules"),
    o("Onvoldoende informatie", "Informations insuffisantes", "Not enough information"),
    o("Probleem met een afspraak", "Problème avec un rendez-vous", "Problem with an appointment"),
    o("Technische storing", "Panne technique", "Technical issue"),
  ],
  ontvangst: [o("E-mail", "E-mail", "Email"), o("WhatsApp", "WhatsApp", "WhatsApp"), o("CRM-melding", "Notification CRM", "CRM notification")],
  magVoorstellen: [
    o("Een afspraak", "Un rendez-vous", "An appointment"),
    o("Een consult", "Une consultation", "A consultation"),
    o("Een andere passende behandeling", "Un autre soin adapté", "Another suitable treatment"),
    o("Pakketten", "Forfaits", "Packages"),
    o("Actieve promoties", "Promotions en cours", "Current promotions"),
  ],
  stijl: [
    o("Zeer informeel", "Très informel", "Very informal"),
    o("Informeel maar professioneel", "Informel mais professionnel", "Informal but professional"),
    o("Warm en persoonlijk", "Chaleureux et personnel", "Warm and personal"),
    o("Neutraal en professioneel", "Neutre et professionnel", "Neutral and professional"),
    o("Formeel", "Formel", "Formal"),
  ],
  aanspreekvorm: [o("Je", "Tu", "Informal"), o("U", "Vous", "Formal")],
};

const nl = {
  titel: "Vragenlijst voor uw AI-receptionist",
  titelMetNaam: (naam: string) => `Vragenlijst voor de AI-receptionist van ${naam}`,
  uitlegNieuw:
    "Invullen duurt ongeveer 30 minuten. U kunt tussendoor stoppen: uw antwoorden blijven bewaard en u gaat later gewoon verder via dezelfde link. Weet u iets niet zeker, laat het dan open. Wij vullen niets zelf in en de AI verzint nooit iets.",
  uitlegBewerken:
    "Pas aan wat nodig is en klik op Opslaan. Uw AI-receptionist gebruikt de nieuwe informatie meteen. Weet u iets niet zeker, laat het dan open: de AI verzint nooit iets.",
  stappen: [
    "Bedrijf en kanalen",
    "Vestigingen",
    "Behandelingen en consulten",
    "Afspraken en annuleren",
    "Grenzen en overdracht",
    "Toon, vragen en systemen",
    "Nakijken en versturen",
  ],
  verwijderen: "Verwijderen",
  // stap 1
  bedrijfsnaam: "Bedrijfsnaam",
  website: "Website",
  contactpersoon: "Contactpersoon",
  email: "E-mail",
  telefoon: "Telefoon",
  instagram: "Instagram-account",
  facebook: "Facebook-pagina",
  whatsapp: "WhatsApp-nummer",
  goedkeurder: "Wie keurt de teksten goed?",
  talen: "In welke talen moet de AI antwoorden?",
  andereTaal: "Andere taal",
  andereTaalHint: "Spreekt u klanten ook in een andere taal aan, vul die hier in. Andere talen bespreken we samen.",
  andereTaalPlaats: "Bijvoorbeeld Spaans of Duits",
  // stap 2
  vestigingenIntro: "Vul één blok in per vestiging. Klik onderaan om er een toe te voegen.",
  vestiging: (n: number) => `Vestiging ${n}`,
  naam: "Naam",
  adres: "Adres",
  openingstijden: "Openingstijden",
  telefoonOfEmail: "Telefoon of e-mail",
  boekingslink: "Boekingslink of agenda",
  behandelingenHier: "Welke behandelingen hier",
  vestigingToevoegen: "Vestiging toevoegen",
  // stap 3
  categorieen: "Welke categorieën gebruikt u, in uw eigen woorden?",
  categorieenHint:
    "Bijvoorbeeld: ontharing, huidverbetering, injectables. De AI toont eerst een categorie en pas daarna de behandelingen.",
  behandeling: (n: number) => `Behandeling ${n}`,
  categorie: "Categorie",
  uitleg: "Korte uitleg (2 zinnen)",
  duur: "Duur",
  prijs: "Prijs of vanaf-prijs",
  consultNodig: "Eerst een consult nodig?",
  magVoorstellenDeze: "Mag de AI deze voorstellen?",
  behandelingToevoegen: "Behandeling toevoegen",
  behandelingenNiet: "Zijn er behandelingen die de AI beter niet noemt?",
  consult: (n: number) => `Consult ${n}`,
  consultNaam: "Naam van het consult",
  waarvoor: "Waarvoor is het bedoeld?",
  gratisOfPrijs: "Gratis of prijs",
  opVestigingen: "Op welke vestigingen",
  consultToevoegen: "Consult toevoegen",
  naConsult: "Wat gebeurt er meteen na een consult?",
  naConsultHint: "Bijvoorbeeld een offerte, een behandelplan of meteen een afspraak.",
  // stap 4
  verplichteGegevens: "Welke klantgegevens zijn verplicht om een afspraak te maken?",
  systeem: "Welk agenda- of afsprakensysteem gebruikt u?",
  agendaToegang: "Mag de AI de vrije momenten uit uw agenda tonen?",
  agendaToegangHint:
    "Dit bepaalt of de AI kan zeggen dat een dag ruim of beperkt beschikbaar is, of alleen kan doorverwijzen.",
  minimumVooraf: "Hoe lang vóór een afspraak moet een klant minimaal boeken?",
  buffer: "Is er een buffer nodig tussen twee afspraken?",
  zelfdeDag: "Mogen klanten dezelfde dag nog boeken?",
  consultVerplicht: "Voor welke behandelingen is eerst een consult nodig?",
  hoeVerVooruit: "Hoe ver vooraf mogen klanten inplannen?",
  andereRegels: "Andere boekingsregels of uitzonderingen?",
  annuleerTermijn: "Hoe lang vooraf moet een klant annuleren of verplaatsen?",
  annuleerKost: "Is er een annuleringskost? Vanaf wanneer en hoeveel?",
  noShow: "Wat gebeurt er bij een no-show?",
  voorschot: "Werkt u met een voorschot?",
  medewerkerAnnuleren: "Wanneer moet een medewerker tussenkomen bij annuleren of verplaatsen?",
  // stap 5
  magZelfstandig: "Wat mag de AI zelfstandig doen?",
  nooitZelfstandig: "Wat mag de AI absoluut nooit zelfstandig doen of beantwoorden?",
  situaties: "Wanneer moet de AI het gesprek altijd overdragen aan een medewerker?",
  ontvangst: "Hoe wilt u een overdracht ontvangen?",
  ontvangstAdres: "Op welk adres of nummer?",
  magVoorstellen: "Mag de AI deze zaken voorstellen?",
  commercieelNooit: "Wat mag de AI commercieel nooit voorstellen?",
  // stap 6
  stijl: "Hoe communiceert u vandaag met klanten?",
  aanspreekvorm: "Welke aanspreekvorm gebruikt de AI?",
  aanspreekvormHint: "De AI houdt één vorm aan, want de teksten liggen vooraf vast.",
  woorden: "Woorden, uitdrukkingen of emoji die de AI wel of niet mag gebruiken",
  faqTitel: "Antwoorden op veelgestelde vragen",
  faqHint: "Vul in wat uw team vandaag zou antwoorden. Geldt het maar voor één behandeling, schrijf die er dan bij.",
  faqVoorbereiding: "Voorbereiding",
  faqNazorg: "Na de behandeling",
  faqPijn: "Pijn of ongemak",
  faqResultaat: "Resultaat en aantal sessies",
  faqDuur: "Duur van een behandeling",
  faqPrijsindicatie: "Prijsindicatie",
  faqNooit: "Waar de AI hier nooit iets over mag zeggen",
  wekelijks: "Vragen die uw team wekelijks krijgt",
  vraagN: (n: number) => `Vraag ${n}`,
  vraag: "Vraag",
  antwoordTeam: "Antwoord van uw team",
  vraagToevoegen: "Vraag toevoegen",
  sysAgenda: "Agenda of boeking",
  sysCrm: "CRM of klantenbestand",
  sysWebsite: "Websiteplatform",
  sysEmail: "E-mail",
  sysBetalingen: "Betalingen",
  sysAndere: "Andere systemen",
  promoties: "Lopende promoties",
  promotiesHint: "Alleen invullen als er een actie loopt. Zo vermeldt de AI nooit een verlopen aanbieding.",
  promotie: (n: number) => `Promotie ${n}`,
  geldigVan: "Geldig van",
  geldigTot: "Geldig tot",
  voorBehandeling: "Behandeling",
  aanbod: "Aanbod",
  voorwaarden: "Voorwaarden",
  promotieToevoegen: "Promotie toevoegen",
  // stap 7
  nakijkenIntro: "Dit sturen we mee. Klopt er iets niet, ga dan terug naar die stap.",
  sBedrijf: "Bedrijf",
  sVestigingen: "Vestigingen",
  sBehandelingen: "Behandelingen",
  sConsulten: "Consulten",
  sFaq: "Veelgestelde vragen",
  sAanspreekvorm: "Aanspreekvorm",
  nogNietIngevuld: "nog niet ingevuld",
  nogNietGekozen: "nog niet gekozen",
  extraInfo: "Iets dat we nog moeten weten?",
  // knoppen en meldingen
  versturen: "Versturen",
  versturenBezig: "Versturen…",
  opslaan: "Opslaan",
  opslaanBezig: "Opslaan…",
  vorige: "Vorige",
  volgende: "Volgende",
  gewijzigd: "U hebt iets gewijzigd. Klik op Opslaan om uw AI-receptionist bij te werken.",
  bewaardServer: (t: string) => `Bewaard om ${t}, u kunt later verder op elk toestel`,
  bewaardToestel: (t: string) => `Bewaard op dit apparaat om ${t}`,
  blijftBewaard: "Uw antwoorden blijven bewaard",
  bijgewerkt: (t: string) => `Opgeslagen om ${t}. Uw AI-receptionist gebruikt de nieuwe informatie vanaf nu.`,
  nietBijgewerkt: (t: string) =>
    `Opgeslagen om ${t}, maar uw AI-receptionist kon nog niet bijgewerkt worden. Wij bekijken het en laten het u weten.`,
  leeg: "Er is niets opgeslagen: het formulier is leeg. Wilt u alles laten verwijderen? Neem dan contact met ons op.",
  foutVersturen:
    "Versturen lukte niet. Probeer het zo nog eens, of laat ons weten dat het niet lukt. Uw antwoorden blijven bewaard op dit apparaat.",
  foutOpslaan: "Opslaan lukte niet. Probeer het zo nog eens. Uw wijzigingen blijven bewaard op dit apparaat.",
  // bedankt en voettekst
  bedanktTitel: "Bedankt, we hebben alles ontvangen",
  bedanktTekst:
    "We bouwen uw AI-receptionist en testen hem op alle kanalen. Daarna krijgt u hem zelf te zien om uit te proberen. Pas na uw goedkeuring gaat hij live. Ontbreekt er nog iets, dan nemen we contact met u op.",
  bedanktLater:
    "Wilt u later iets aanpassen, zoals een prijs of openingsuren? Open dan gewoon dezelfde link, pas het aan en klik op Opslaan. Uw AI-receptionist gebruikt het meteen.",
  vragen: "Vragen of iets onduidelijk? Antwoord gewoon op het bericht waarmee u deze link kreeg.",
  privacy: "Uw antwoorden worden veilig bewaard en alleen gebruikt voor uw AI-receptionist.",
  privacyLink: "Privacybeleid",
};

export type Teksten = typeof nl;

const fr: Teksten = {
  titel: "Questionnaire pour votre réceptionniste IA",
  titelMetNaam: (naam) => `Questionnaire pour la réceptionniste IA ${deFr(naam)}`,
  uitlegNieuw:
    "Comptez environ 30 minutes. Vous pouvez vous arrêter à tout moment : vos réponses sont enregistrées et vous reprenez plus tard via le même lien. En cas de doute, laissez le champ vide. Nous ne remplissons rien à votre place et l'IA n'invente jamais rien.",
  uitlegBewerken:
    "Modifiez ce qui est nécessaire et cliquez sur Enregistrer. Votre réceptionniste IA utilise les nouvelles informations immédiatement. En cas de doute, laissez le champ vide : l'IA n'invente jamais rien.",
  stappen: [
    "Entreprise et canaux",
    "Établissements",
    "Soins et consultations",
    "Rendez-vous et annulation",
    "Limites et transfert",
    "Ton, questions et systèmes",
    "Vérifier et envoyer",
  ],
  verwijderen: "Supprimer",
  bedrijfsnaam: "Nom de l'entreprise",
  website: "Site web",
  contactpersoon: "Personne de contact",
  email: "E-mail",
  telefoon: "Téléphone",
  instagram: "Compte Instagram",
  facebook: "Page Facebook",
  whatsapp: "Numéro WhatsApp",
  goedkeurder: "Qui valide les textes ?",
  talen: "Dans quelles langues l'IA doit-elle répondre ?",
  andereTaal: "Autre langue",
  andereTaalHint: "Vous parlez à vos clients dans une autre langue ? Indiquez-la ici. Nous en discuterons ensemble.",
  andereTaalPlaats: "Par exemple espagnol ou allemand",
  vestigingenIntro: "Remplissez un bloc par établissement. Cliquez en bas pour en ajouter un.",
  vestiging: (n) => `Établissement ${n}`,
  naam: "Nom",
  adres: "Adresse",
  openingstijden: "Heures d'ouverture",
  telefoonOfEmail: "Téléphone ou e-mail",
  boekingslink: "Lien de réservation ou agenda",
  behandelingenHier: "Soins proposés ici",
  vestigingToevoegen: "Ajouter un établissement",
  categorieen: "Quelles catégories utilisez-vous, avec vos propres mots ?",
  categorieenHint:
    "Par exemple : épilation, amélioration de la peau, injectables. L'IA montre d'abord une catégorie, puis les soins.",
  behandeling: (n) => `Soin ${n}`,
  categorie: "Catégorie",
  uitleg: "Courte explication (2 phrases)",
  duur: "Durée",
  prijs: "Prix ou prix à partir de",
  consultNodig: "Consultation préalable nécessaire ?",
  magVoorstellenDeze: "L'IA peut-elle le proposer ?",
  behandelingToevoegen: "Ajouter un soin",
  behandelingenNiet: "Y a-t-il des soins que l'IA ne doit pas mentionner ?",
  consult: (n) => `Consultation ${n}`,
  consultNaam: "Nom de la consultation",
  waarvoor: "À quoi sert-elle ?",
  gratisOfPrijs: "Gratuite ou prix",
  opVestigingen: "Dans quels établissements",
  consultToevoegen: "Ajouter une consultation",
  naConsult: "Que se passe-t-il juste après une consultation ?",
  naConsultHint: "Par exemple un devis, un plan de traitement ou directement un rendez-vous.",
  verplichteGegevens: "Quelles données client sont obligatoires pour prendre rendez-vous ?",
  systeem: "Quel agenda ou système de rendez-vous utilisez-vous ?",
  agendaToegang: "L'IA peut-elle afficher les créneaux libres de votre agenda ?",
  agendaToegangHint:
    "Cela détermine si l'IA peut dire qu'une journée est largement ou peu disponible, ou seulement rediriger.",
  minimumVooraf: "Combien de temps à l'avance un client doit-il réserver au minimum ?",
  buffer: "Faut-il un temps tampon entre deux rendez-vous ?",
  zelfdeDag: "Les clients peuvent-ils réserver le jour même ?",
  consultVerplicht: "Pour quels soins une consultation préalable est-elle nécessaire ?",
  hoeVerVooruit: "Jusqu'à combien de temps à l'avance les clients peuvent-ils réserver ?",
  andereRegels: "Autres règles de réservation ou exceptions ?",
  annuleerTermijn: "Combien de temps à l'avance un client doit-il annuler ou déplacer ?",
  annuleerKost: "Y a-t-il des frais d'annulation ? À partir de quand et combien ?",
  noShow: "Que se passe-t-il en cas d'absence sans prévenir ?",
  voorschot: "Demandez-vous un acompte ?",
  medewerkerAnnuleren: "Quand un collaborateur doit-il intervenir pour une annulation ou un report ?",
  magZelfstandig: "Que peut faire l'IA de manière autonome ?",
  nooitZelfstandig: "Que l'IA ne doit-elle jamais faire ou répondre seule ?",
  situaties: "Quand l'IA doit-elle toujours transférer la conversation à un collaborateur ?",
  ontvangst: "Comment souhaitez-vous recevoir un transfert ?",
  ontvangstAdres: "À quelle adresse ou quel numéro ?",
  magVoorstellen: "L'IA peut-elle proposer ceci ?",
  commercieelNooit: "Que l'IA ne doit-elle jamais proposer commercialement ?",
  stijl: "Comment communiquez-vous aujourd'hui avec vos clients ?",
  aanspreekvorm: "L'IA doit-elle tutoyer ou vouvoyer ?",
  aanspreekvormHint: "L'IA garde une seule forme, car les textes sont fixés à l'avance.",
  woorden: "Mots, expressions ou emoji que l'IA peut ou ne peut pas utiliser",
  faqTitel: "Réponses aux questions fréquentes",
  faqHint: "Indiquez ce que votre équipe répondrait aujourd'hui. Si cela ne concerne qu'un soin, précisez lequel.",
  faqVoorbereiding: "Préparation",
  faqNazorg: "Après le soin",
  faqPijn: "Douleur ou inconfort",
  faqResultaat: "Résultat et nombre de séances",
  faqDuur: "Durée d'un soin",
  faqPrijsindicatie: "Indication de prix",
  faqNooit: "Ce dont l'IA ne doit jamais parler ici",
  wekelijks: "Questions que votre équipe reçoit chaque semaine",
  vraagN: (n) => `Question ${n}`,
  vraag: "Question",
  antwoordTeam: "Réponse de votre équipe",
  vraagToevoegen: "Ajouter une question",
  sysAgenda: "Agenda ou réservation",
  sysCrm: "CRM ou fichier clients",
  sysWebsite: "Plateforme du site",
  sysEmail: "E-mail",
  sysBetalingen: "Paiements",
  sysAndere: "Autres systèmes",
  promoties: "Promotions en cours",
  promotiesHint: "À remplir seulement si une promotion est en cours. Ainsi l'IA ne mentionne jamais une offre expirée.",
  promotie: (n) => `Promotion ${n}`,
  geldigVan: "Valable du",
  geldigTot: "Valable jusqu'au",
  voorBehandeling: "Soin",
  aanbod: "Offre",
  voorwaarden: "Conditions",
  promotieToevoegen: "Ajouter une promotion",
  nakijkenIntro: "Voici ce que nous envoyons. Si quelque chose ne va pas, revenez à cette étape.",
  sBedrijf: "Entreprise",
  sVestigingen: "Établissements",
  sBehandelingen: "Soins",
  sConsulten: "Consultations",
  sFaq: "Questions fréquentes",
  sAanspreekvorm: "Tutoiement ou vouvoiement",
  nogNietIngevuld: "pas encore rempli",
  nogNietGekozen: "pas encore choisi",
  extraInfo: "Autre chose que nous devrions savoir ?",
  versturen: "Envoyer",
  versturenBezig: "Envoi…",
  opslaan: "Enregistrer",
  opslaanBezig: "Enregistrement…",
  vorige: "Précédent",
  volgende: "Suivant",
  gewijzigd: "Vous avez modifié quelque chose. Cliquez sur Enregistrer pour mettre à jour votre réceptionniste IA.",
  bewaardServer: (t) => `Enregistré à ${t}, vous pouvez continuer plus tard sur n'importe quel appareil`,
  bewaardToestel: (t) => `Enregistré sur cet appareil à ${t}`,
  blijftBewaard: "Vos réponses restent enregistrées",
  bijgewerkt: (t) => `Enregistré à ${t}. Votre réceptionniste IA utilise désormais ces nouvelles informations.`,
  nietBijgewerkt: (t) =>
    `Enregistré à ${t}, mais votre réceptionniste IA n'a pas encore pu être mise à jour. Nous vérifions et revenons vers vous.`,
  leeg: "Rien n'a été enregistré : le formulaire est vide. Vous souhaitez tout supprimer ? Contactez-nous.",
  foutVersturen:
    "L'envoi n'a pas fonctionné. Réessayez dans un instant ou prévenez-nous si cela persiste. Vos réponses restent enregistrées sur cet appareil.",
  foutOpslaan: "L'enregistrement n'a pas fonctionné. Réessayez dans un instant. Vos modifications restent sur cet appareil.",
  bedanktTitel: "Merci, nous avons tout reçu",
  bedanktTekst:
    "Nous construisons votre réceptionniste IA et la testons sur tous les canaux. Vous pourrez ensuite l'essayer vous-même. Elle ne sera mise en ligne qu'après votre accord. S'il manque quelque chose, nous vous contacterons.",
  bedanktLater:
    "Vous souhaitez modifier quelque chose plus tard, comme un prix ou des horaires ? Ouvrez simplement le même lien, modifiez et cliquez sur Enregistrer. Votre réceptionniste IA l'utilise aussitôt.",
  vragen: "Une question ? Répondez simplement au message par lequel vous avez reçu ce lien.",
  privacy: "Vos réponses sont conservées en toute sécurité et utilisées uniquement pour votre réceptionniste IA.",
  privacyLink: "Politique de confidentialité",
};

const en: Teksten = {
  titel: "Questionnaire for your AI receptionist",
  titelMetNaam: (naam) => `Questionnaire for ${naam}'s AI receptionist`,
  uitlegNieuw:
    "It takes about 30 minutes. You can stop at any time: your answers are saved and you can continue later via the same link. If you're unsure about something, leave it blank. We don't fill anything in for you and the AI never makes anything up.",
  uitlegBewerken:
    "Change what you need and click Save. Your AI receptionist uses the new information straight away. If you're unsure, leave it blank: the AI never makes anything up.",
  stappen: [
    "Business and channels",
    "Locations",
    "Treatments and consultations",
    "Appointments and cancellations",
    "Limits and handover",
    "Tone, questions and systems",
    "Review and send",
  ],
  verwijderen: "Remove",
  bedrijfsnaam: "Business name",
  website: "Website",
  contactpersoon: "Contact person",
  email: "Email",
  telefoon: "Phone",
  instagram: "Instagram account",
  facebook: "Facebook page",
  whatsapp: "WhatsApp number",
  goedkeurder: "Who approves the texts?",
  talen: "Which languages should the AI answer in?",
  andereTaal: "Other language",
  andereTaalHint: "Do you also speak to clients in another language? Add it here. We'll discuss other languages together.",
  andereTaalPlaats: "For example Spanish or German",
  vestigingenIntro: "Fill in one block per location. Click below to add another.",
  vestiging: (n) => `Location ${n}`,
  naam: "Name",
  adres: "Address",
  openingstijden: "Opening hours",
  telefoonOfEmail: "Phone or email",
  boekingslink: "Booking link or calendar",
  behandelingenHier: "Treatments offered here",
  vestigingToevoegen: "Add a location",
  categorieen: "Which categories do you use, in your own words?",
  categorieenHint: "For example: hair removal, skin improvement, injectables. The AI shows a category first, then the treatments.",
  behandeling: (n) => `Treatment ${n}`,
  categorie: "Category",
  uitleg: "Short explanation (2 sentences)",
  duur: "Duration",
  prijs: "Price or starting price",
  consultNodig: "Consultation needed first?",
  magVoorstellenDeze: "May the AI suggest this?",
  behandelingToevoegen: "Add a treatment",
  behandelingenNiet: "Are there treatments the AI should not mention?",
  consult: (n) => `Consultation ${n}`,
  consultNaam: "Name of the consultation",
  waarvoor: "What is it for?",
  gratisOfPrijs: "Free or price",
  opVestigingen: "At which locations",
  consultToevoegen: "Add a consultation",
  naConsult: "What happens right after a consultation?",
  naConsultHint: "For example a quote, a treatment plan or an appointment straight away.",
  verplichteGegevens: "Which client details are required to book an appointment?",
  systeem: "Which calendar or booking system do you use?",
  agendaToegang: "May the AI show the free slots in your calendar?",
  agendaToegangHint: "This decides whether the AI can say a day has plenty or limited availability, or can only refer people on.",
  minimumVooraf: "How far ahead must a client book at minimum?",
  buffer: "Is a buffer needed between two appointments?",
  zelfdeDag: "Can clients book on the same day?",
  consultVerplicht: "Which treatments require a consultation first?",
  hoeVerVooruit: "How far in advance can clients book?",
  andereRegels: "Other booking rules or exceptions?",
  annuleerTermijn: "How far ahead must a client cancel or reschedule?",
  annuleerKost: "Is there a cancellation fee? From when and how much?",
  noShow: "What happens with a no-show?",
  voorschot: "Do you ask for a deposit?",
  medewerkerAnnuleren: "When should a staff member step in for cancellations or rescheduling?",
  magZelfstandig: "What may the AI do on its own?",
  nooitZelfstandig: "What must the AI never do or answer on its own?",
  situaties: "When must the AI always hand the conversation to a staff member?",
  ontvangst: "How would you like to receive a handover?",
  ontvangstAdres: "To which address or number?",
  magVoorstellen: "May the AI suggest these?",
  commercieelNooit: "What must the AI never suggest commercially?",
  stijl: "How do you communicate with clients today?",
  aanspreekvorm: "How formally should the AI address clients?",
  aanspreekvormHint: "The AI sticks to one form, because the texts are set in advance.",
  woorden: "Words, expressions or emoji the AI may or may not use",
  faqTitel: "Answers to frequently asked questions",
  faqHint: "Write what your team would answer today. If it only applies to one treatment, mention which.",
  faqVoorbereiding: "Preparation",
  faqNazorg: "After the treatment",
  faqPijn: "Pain or discomfort",
  faqResultaat: "Results and number of sessions",
  faqDuur: "Duration of a treatment",
  faqPrijsindicatie: "Price indication",
  faqNooit: "What the AI must never say about this",
  wekelijks: "Questions your team gets every week",
  vraagN: (n) => `Question ${n}`,
  vraag: "Question",
  antwoordTeam: "Your team's answer",
  vraagToevoegen: "Add a question",
  sysAgenda: "Calendar or booking",
  sysCrm: "CRM or client database",
  sysWebsite: "Website platform",
  sysEmail: "Email",
  sysBetalingen: "Payments",
  sysAndere: "Other systems",
  promoties: "Current promotions",
  promotiesHint: "Only fill in if a promotion is running. That way the AI never mentions an expired offer.",
  promotie: (n) => `Promotion ${n}`,
  geldigVan: "Valid from",
  geldigTot: "Valid until",
  voorBehandeling: "Treatment",
  aanbod: "Offer",
  voorwaarden: "Conditions",
  promotieToevoegen: "Add a promotion",
  nakijkenIntro: "This is what we'll send. If something's wrong, go back to that step.",
  sBedrijf: "Business",
  sVestigingen: "Locations",
  sBehandelingen: "Treatments",
  sConsulten: "Consultations",
  sFaq: "Frequently asked questions",
  sAanspreekvorm: "Form of address",
  nogNietIngevuld: "not filled in yet",
  nogNietGekozen: "not chosen yet",
  extraInfo: "Anything else we should know?",
  versturen: "Send",
  versturenBezig: "Sending…",
  opslaan: "Save",
  opslaanBezig: "Saving…",
  vorige: "Previous",
  volgende: "Next",
  gewijzigd: "You changed something. Click Save to update your AI receptionist.",
  bewaardServer: (t) => `Saved at ${t}, you can continue later on any device`,
  bewaardToestel: (t) => `Saved on this device at ${t}`,
  blijftBewaard: "Your answers are kept",
  bijgewerkt: (t) => `Saved at ${t}. Your AI receptionist now uses the new information.`,
  nietBijgewerkt: (t) =>
    `Saved at ${t}, but your AI receptionist could not be updated yet. We're looking into it and will let you know.`,
  leeg: "Nothing was saved: the form is empty. Want everything removed? Please contact us.",
  foutVersturen: "Sending didn't work. Please try again shortly, or let us know if it keeps failing. Your answers are kept on this device.",
  foutOpslaan: "Saving didn't work. Please try again shortly. Your changes are kept on this device.",
  bedanktTitel: "Thank you, we've received everything",
  bedanktTekst:
    "We're building your AI receptionist and testing it on every channel. Then you get to try it yourself. It only goes live after your approval. If anything is missing, we'll get in touch.",
  bedanktLater:
    "Want to change something later, like a price or opening hours? Just open the same link, make the change and click Save. Your AI receptionist uses it straight away.",
  vragen: "Questions? Just reply to the message this link came with.",
  privacy: "Your answers are stored securely and used only for your AI receptionist.",
  privacyLink: "Privacy policy",
};

export const TEKSTEN: Record<Taal, Teksten> = { nl, fr, en };
