/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeheerRouteImport } from './routes/beheer'
import { Route as ChatTestRouteImport } from './routes/chat-test'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IntakeCodeRouteImport } from './routes/intake.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerRoute = BeheerRouteImport.update({
  id: '/beheer',
  path: '/beheer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatTestRoute = ChatTestRouteImport.update({
  id: '/chat-test',
  path: '/chat-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeCodeRoute = IntakeCodeRouteImport.update({
  id: '/intake/$code',
  path: '/intake/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beheer': typeof BeheerRoute
  '/chat-test': typeof ChatTestRoute
  '/privacy': typeof PrivacyRoute
  '/intake/$code': typeof IntakeCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beheer': typeof BeheerRoute
  '/chat-test': typeof ChatTestRoute
  '/privacy': typeof PrivacyRoute
  '/intake/$code': typeof IntakeCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beheer': typeof BeheerRoute
  '/chat-test': typeof ChatTestRoute
  '/privacy': typeof PrivacyRoute
  '/intake/$code': typeof IntakeCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/beheer' | '/chat-test' | '/privacy' | '/intake/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/beheer' | '/chat-test' | '/privacy' | '/intake/$code'
  id: '__root__' | '/' | '/beheer' | '/chat-test' | '/privacy' | '/intake/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeheerRoute: typeof BeheerRoute
  ChatTestRoute: typeof ChatTestRoute
  PrivacyRoute: typeof PrivacyRoute
  IntakeCodeRoute: typeof IntakeCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer': {
      id: '/beheer'
      path: '/beheer'
      fullPath: '/beheer'
      preLoaderRoute: typeof BeheerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-test': {
      id: '/chat-test'
      path: '/chat-test'
      fullPath: '/chat-test'
      preLoaderRoute: typeof ChatTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$code': {
      id: '/intake/$code'
      path: '/intake/$code'
      fullPath: '/intake/$code'
      preLoaderRoute: typeof IntakeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeheerRoute: BeheerRoute,
  ChatTestRoute: ChatTestRoute,
  PrivacyRoute: PrivacyRoute,
  IntakeCodeRoute: IntakeCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
